### PR TITLE
bugfix: numfmt '--padding cannot be combined with --format'

### PR DESCRIPTION
**Pull request by coderofsalvation**
got error on my Ubuntu 14.04.1 LTS, but works with this fix

### CODE REVIEW

**Comment by D630** [comment]
Hey, thank you for pointing that out!

Yes, it works with your fix/without `--padding`. But on Debian Testing I cannot reproduce that bug:

```sh
% command find -L / \
    -mindepth 1 \
    -maxdepth 1 \
    \( -xtype l -a -printf "l%y %s %A@ %T@ %C@ |%P\n" \) \
    -prune \
    -o \
    -printf "r%y %s %A@ %T@ %C@ |%P\n" \
  |& command sed "s|^find: .\(.*\)/\([^/]*\)': Permission denied$|ll 0 0  0 0 \|\2|" \
  |  command sort --stable -u -k 6 \
  |  command numfmt --delimiter=' ' \
         --field=2 \
         --format='%4f' \
         --from=none \
         --from-unit=1 \
         --invalid=warn \
         --padding=4 \
         --round=from-zero \
         --to=iec \
         --to-unit=1 \
  1>/dev/null
>
```

 I am using this version of `numfmt`:

```
% numfmt --version | head -n1
> numfmt (GNU coreutils) 8.23
```

But on [Ubuntu Trusty](https://launchpad.net/ubuntu/trusty/+package/coreutils)  version 8.21 seems to be available. In [8.23](http://savannah.gnu.org/news/?group=coreutils) there were some changes, which have been affected `numfmt`:

```sh
% wget -O - https://lists.gnu.org/archive/html/coreutils-announce/2014-07/msg00000.html \
   | w3m -dump -T text/html \
   | less -Rp numfmt
```

See also http://git.savannah.gnu.org/cgit/coreutils.git/log/?qt=grep&q=numfmt

**Comment by coderofsalvation** [comment]
$ numfmt --version | head -n1
numfmt (GNU coreutils) 8.2

your theory is correct for Ubuntu 14.04.1 LTS

**Comment by D630** [comment]
Ok. It was commit [10a9652](http://git.savannah.gnu.org/cgit/coreutils.git/commit/src/numfmt.c?id=10a96524355775e6d8533555f185656c7f29075c), part of 8.23

**Comment by coderofsalvation** [comment]
thanks

**Pull request merged**
